# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image with Yarn pre-installed
FROM node:20-alpine AS build

# Set the working directory
WORKDIR /app

# Copy the package and yarn lock files to the container
COPY package.json yarn.lock ./

# Install the dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the application source code to the container
COPY . .

# Build the TypeScript code
RUN yarn build

# Use a smaller Node.js image for the final runtime container
FROM node:20-alpine AS runtime

# Set the working directory
WORKDIR /app

# Copy over the built application and node_modules from the build stage
COPY --from=build /app/build /app/build
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/package.json /app/package.json

# Set the command to run the application
CMD ["node", "build/index.js"]
